### ISSUE TITLE
Add "How to build/run" on README

### ISSUE THREAD

**Issue by filfreire** [javirk/Dino-AI#1]
Hi @javirk 👋 

I suggest you add to the README information on how to build/run this project locally, also the versions of any dependencies, so anyone who'd like to contribute finds it easier to test locally.

Nice project 👍 👏

**Comment by javirk** [comment]
Hi @filfreire!

Yes, I'm working on it, I didn't have time to do it. 

Thank you! i'll keep this updated!

**Comment by javirk** [comment]
Done! Let me know if you have any doubts!
